blog/config/routes.rb
Rails.application.routes.draw do
  get 'static_page/home'

  get 'spellcheck/:term' => 'dictionary_words#spellcheck'

  resources :comments
  resources :blogposts
  root 'blogposts#index'

end

blog/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :blogpost
end

blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # Commit

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:commenttext, :author, :blogpost_id)
    end
end

blog/app/helpers/comments_helper.rb
module CommentsHelper
end

blog/app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :commenttext %><br>
    <%= f.text_area :commenttext %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :blogpost_id %><br>
    <%= f.number_field :blogpost_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

blog/app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

blog/app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Commenttext</th>
      <th>Author</th>
      <th>Blogpost</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  	<div class = "boxed"
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.commenttext %></td>
        <td><%= comment.author %></td>
        <td><%= comment.blogpost_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </div>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

blog/app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

blog/app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Commenttext:</strong>
  <%= @comment.commenttext %>
</p>

<p>
  <strong>Author:</strong>
  <%= @comment.author %>
</p>

<div class = "boxed">
<p>
  <strong>Blogpost:</strong>
  <%= @comment.blogpost_id %>
</p>
</div>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>